apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: IPPool
metadata:
  name: kng-ip-pool
  namespace: default
  labels:
    loadbalancer.harvesterhci.io/global-ip-pool: "false"
    loadbalancer.harvesterhci.io/vid: "8"
spec:
  ranges:
    - gateway: 10.0.2.1
      rangeStart: 10.0.2.200
      rangeEnd: 10.0.2.240
      subnet: 10.0.2.0/24
  selector:
    network: default/kng-internal
    scope:
      - guestCluster: "kubernetes"
        namespace: "kng-vms"
        project: "c-qk74j/p-5sjdh"
