resources:
  - cloudinit-secret.yaml
  - ../base
patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: base-vm-disk
    patch: |-
      - op: replace
        path: /metadata/name
        value: kng-04-disk
      - op: add
        path: /metadata/labels/recurring-job-group.longhorn.io~1kng-vms
        value: "enabled"
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: base-vm
    patch: |-
      - op: replace
        path: /metadata/name
        value: kng-04
      - op: replace
        path: /metadata/labels/vm.kng.house~1role
        value: worker-node
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1component
        value: worker-node
      - op: replace
        path: /spec/template/spec/hostname
        value: kng-04
      - op: replace
        path: /spec/template/spec/domain/cpu/cores
        value: 4
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 12Gi
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: kng-04-disk
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud/secretRef/name
        value: kng01-cloudinit-secret
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud/networkDataSecretRef/name
        value: kng01-cloudinit-secret
