resources:
  - ../worker-nodes
patches:
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: base-vm
    patch: |-
      - op: replace
        path: /metadata/name
        value: kng-04
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: kng-04
    path: patch.yaml