apiVersion: v1
kind: Secret
metadata:
  name: cloudinit-secret
  namespace: default
type: Opaque
stringData:
  userdata: |
    #cloud-config
    ssh_pwauth: true
    users:
      - name: root
        lock_passwd: false
        passwd: $6$MA6v7JyQGJABpN4F$eNXET.twXmaFBetvuqbxR5Vd7TjZkKrbE33keFr.XygHjyq220/cUyvIVFWp9hUhG66oh4lFum9V1jdQt4A/6.
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE4SrYkfM8Xu/9cFpqIOb8Y4OJ3WyPYJRB1zMOoTPJQN george@Georgioss-MacBook-Pro.local
    chpasswd:
      expire: false
      list: |
        root:$6$MA6v7JyQGJABpN4F$eNXET.twXmaFBetvuqbxR5Vd7TjZkKrbE33keFr.XygHjyq220/cUyvIVFWp9hUhG66oh4lFum9V1jdQt4A/6.
    runcmd:
      - [ /usr/sbin/transactional-update, "-n", "run", "sh", "-c", "zypper -n in qemu-guest-agent && systemctl enable qemu-guest-agent.service" ]
    power_state:
      mode: reboot
      message: "Reboot to activate QGA snapshot"
      timeout: 30
      condition: true