namespace: kng-cluster
secretGenerator:
  - name: cloudinit-secret
    namespace: kng-cluster
    files:
      - userdata=k3s-cloud-init.txt

generatorOptions:
  disableNameSuffixHash: true

resources:
  - c1
  - c2
  - c3
  - w1
  - w2
  - w3
  