namespace: kng-cluster
secretGenerator:
  - name: cloudinit-secret
    namespace: kng-cluster
    files:
      - userdata=cloud-init

generatorOptions:
  disableNameSuffixHash: true

resources:
  - kng-01
  - kng-02
  - kng-03
  - kng-04
  - kng-05
  - kng-06
  