apiVersion: v1
kind: LimitRange
metadata:
  name: vm-defaults
  namespace: default
spec:
  limits:
  - type: Container
    default:
      cpu: "2000m"
      memory: "4Gi"
    defaultRequest:
      cpu: "1500m"
      memory: "3Gi"
    max:
      cpu: "12000m"
      memory: "24Gi"
    min:
      cpu: "5m"
      memory: "32Mi"
  - type: Pod
    min:
      cpu: "500m"
      memory: "2Gi"