apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: base-vm
  labels:
    vm.kng.house/role: control-plane
    app.kubernetes.io/component: control-plane
spec:
  template:
    metadata:
      labels:
        vm.kng.house/role: control-plane
        app.kubernetes.io/component: control-plane
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 2
          threads: 1
        memory:
          guest: 16Gi
        resources:
          limits:
            cpu: "2"
            memory: 16Gi
          requests:
            cpu: "2"
            memory: 16Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: control-plane