resources:
  - ../base-cp
patches:
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: base-vm
    patch: |-
      - op: replace
        path: /metadata/name
        value: c2
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: c2
    path: patch.yaml