apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: kng-06
  labels:
    vm.kng.house/role: worker-node
    app.kubernetes.io/component: worker-node
spec:
  template:
    metadata:
      labels:
        vm.kng.house/role: worker-node
        app.kubernetes.io/component: worker-node
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: worker-node
# lightweight node
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-pool
                    operator: In
                    values: ["2p5g"]
      hostname: kng-06
      domain:
        cpu:
          sockets: 1
          cores: 4
          threads: 1
        memory:
          guest: 12Gi
        resources:
          requests: { cpu: "2000m", memory: "12Gi" }
          limits:   { cpu: "4000m", memory: "12Gi" }
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: kng-06-disk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: kng-06-cloudinit-secret