apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: base-vm-disk
  labels:
    recurring-job.longhorn.io/source: "enabled"
    harvesterhci.io/imageId: default/microos-openstack
spec:
  accessModes: ["ReadWriteMany"]
  volumeMode: Block
  storageClassName: longhorn-microos-openstack
  resources:
    requests:
      storage: 64Gi
