apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: base-vm
  namespace: default
  annotations:
    harvesterhci.io/vmRunStrategy: RerunOnFailure
    harvesterhci.io/os: linux
    harvesterhci.io/maintain-mode-strategy: ShutdownAndRestartAfterEnable
spec:
  runStrategy: RerunOnFailure
  dataVolumeTemplates:
    - metadata:
        name: base-vm-disk
      spec:
        source:
          blank: {}
        storage:
          storageClassName: longhorn-microos-openstack
          accessModes: ["ReadWriteMany"]
          volumeMode: Block
          resources:
            requests:
              storage: 64Gi
  template:
    spec:
      hostname: base-vm
      terminationGracePeriodSeconds: 120
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        memory:
          guest: 2Gi
      devices:
        disks:
          - name: disk-0
            bootOrder: 1
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
        interfaces:
          - name: default
            bridge: {}
            model: virtio
      networks:
        - name: default
          multus:
            networkName: kng-cluster/k8s-network
      volumes:
        - name: disk-0
          dataVolume:
            name: base-vm-disk
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkDataSecretRef:
              name: cloudinit-secret
            secretRef:
              name: cloudinit-secret
