resources:
  - ../base-wrk
patches:
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: base-vm
    patch: |-
      - op: replace
        path: /metadata/name
        value: w1
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: w1
    path: patch.yaml