labels:
  vms.kng.house/bundle: infra-common

defaultNamespace: default
targetCustomizations:
  - name: local-only
    clusterSelector:
      matchLabels:
        management.cattle.io/cluster-name: local
    kustomize:
      dir: .

