resources:
   - ../control-planes
patches:
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: base-vm
    patch: |-
      - op: replace
        path: /metadata/name
        value: kng-03
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: kng-03
    path: patch.yaml