resources:
  - cloudinit-secret.yaml
  - ../base
patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: base-vm-disk
    patch: |-
      - op: replace
        path: /metadata/name
        value: kng-03-disk
      - op: add
        path: /metadata/labels/recurring-job-group.longhorn.io~1kng-vms
        value: "enabled"
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: base-vm
    patch: |-
      - op: replace
        path: /metadata/name
        value: kng-03
      - op: replace
        path: /metadata/labels/vm.kng.house~1role
        value: control-plane
      - op: replace
        path: /metadata/labels/app.kubernetes.io~1component
        value: control-plane
      - op: add
        path: /spec/template/spec/affinity/podAntiAffinity
        value:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/component
                    operator: In
                    values: ["control-plane"]
              topologyKey: kubernetes.io/hostname
      - op: replace
        path: /spec/template/spec/hostname
        value: kng-03
      - op: replace
        path: /spec/template/spec/domain/cpu/cores
        value: 2
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 8Gi
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: kng-03-disk
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud/secretRef/name
        value: kng01-cloudinit-secret
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud/networkDataSecretRef/name
        value: kng01-cloudinit-secret
