apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: base-vm
  labels:
    vm.kng.house/role: worker-node
    app.kubernetes.io/component: worker-node
spec:
  template:
    metadata:
      labels:
        vm.kng.house/role: worker-node
        app.kubernetes.io/component: worker-node
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: worker-node
      domain:
        cpu:
          sockets: 1
          cores: 8
          threads: 1
        memory:
          guest: 16Gi
        resources:
          requests: { cpu: "2000m", memory: "16Gi" }
          limits:   { cpu: "8000m", memory: "16Gi" }