resources:
   - ../base-cp
patches:
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: base-vm
    patch: |-
      - op: replace
        path: /metadata/name
        value: c3
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: c3
    path: patch.yaml