apiVersion: v1
kind: Secret
metadata:
  name: cloudinit-common
  namespace: kng-cluster
type: Opaque
stringData:
  networkdata: |
    version: 2
    ethernets:
      eth0:
        match: { name: "e*" }
        set-name: eth0
        dhcp4: false
        addresses: [10.0.2.50/24]
        routes:
          - to: 0.0.0.0/0
            via: 10.0.2.1
        nameservers:
          addresses: [10.0.1.1,1.1.1.1]
  userdata: |
    #cloud-config
    ssh_pwauth: true
    users:
      - default
      - name: george
        groups: [sudo]
        shell: /bin/bash
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        passwd: "$6$uFhQ0e7WahIYsNCE$bQXrGTYjLXVBZQdaubgCwnznEtmR79dX2yqyF107ZhJ9B1LXR2emEbhPojPtQiJ6IMDJ6nndFbZVGpcmJtGaa."
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE4SrYkfM8Xu/9cFpqIOb8Y4OJ3WyPYJRB1zMOoTPJQN george@Georgioss-MacBook-Pro.local
    chpasswd:
      expire: false
      list: |
        root:$6$uFhQ0e7WahIYsNCE$bQXrGTYjLXVBZQdaubgCwnznEtmR79dX2yqyF107ZhJ9B1LXR2emEbhPojPtQiJ6IMDJ6nndFbZVGpcmJtGaa.
    write_files:
      - path: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          overlay
      - path: /etc/sysctl.d/99-k8s.conf
        content: |
          net.ipv4.ip_forward=1
          net.bridge.bridge-nf-call-iptables=1
          net.bridge.bridge-nf-call-ip6tables=1

    package_update: true
    package_upgrade: true
    package_reboot_if_required: true
    packages:
      - openssh-server 
      - qemu-guest-agent
      - curl
      - open-iscsi
      - nfs-common
    runcmd:
      - systemctl enable --now qemu-guest-agent
      - systemctl enable --now iscsid || true
      - swapoff -a
      - sed -i '/\sswap\s/ s/^/#/' /etc/fstab
    power_state:
      delay: "+15"
      mode: reboot
      message: "Rebooting!"
      timeout: 30
      condition: true