apiVersion: v1
kind: Secret
metadata:
  name: microos1-cloudinit
  namespace: default
type: Opaque
stringData:
  userdata: |
      #cloud-config
      password: root123
      disable_root: false
      ssh_pwauth: true
      packages:
        - qemu-guest-agent
  networkdata: |
    version: 2
    ethernets:
      enp1s0:
        dhcp4: true