apiVersion: v1
kind: Secret
metadata:
  name: microos1-cloudinit
  namespace: default
type: Opaque
stringData:
  userdata: |
      #cloud-config
      ssh_pwauth: true
      chpasswd:
        expire: false
        list: |
          root:$6$rounds=4096$gIHRK7SwqpWSM3L5$gCwEJpVmODsdXwN8wqSeKc5pRJym.qWb9k1ai9rMC2zpjD4fwZdw82zXoDqG4LPjoxEYQx1nZrJ1AUVywwv3O1
      runcmd:
        - [ sh, -c, 'transactional-update -n pkg install qemu-guest-agent' ]
        - [ sh, -c, 'transactional-update -n run systemctl enable qemu-guest-agent.service' ]
        # ^ enable inside the new root so it persists after reboot
      power_state:
        mode: reboot
        message: "Rebooting to activate qemu-guest-agent (MicroOS transactional root)"
        timeout: 30
        condition: true

  networkdata: |
    version: 2
    ethernets:
      enp1s0:
        dhcp4: true