apiVersion: v1
kind: ConfigMap
metadata:
  name: default-init
  namespace: kng-cluster
  annotations:
    field.cattle.io/description: Default Cloud Init for RKE2
  labels:
    harvesterhci.io/cloud-init-template: user
data:
  cloudInit: |2-
        #cloud-config
        hostname: default-host
        manage_etc_hosts: true
        ssh_pwauth: true
        users:
          - name: george
            groups: [sudo]
            shell: /bin/bash
            sudo: ALL=(ALL) NOPASSWD:ALL
            lock_passwd: false
            passwd: "$6$uFhQ0e7WahIYsNCE$bQXrGTYjLXVBZQdaubgCwnznEtmR79dX2yqyF107ZhJ9B1LXR2emEbhPojPtQiJ6IMDJ6nndFbZVGpcmJtGaa."
            ssh_authorized_keys:
              - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE4SrYkfM8Xu/9cFpqIOb8Y4OJ3WyPYJRB1zMOoTPJQN george@Georgioss-MacBook-Pro.local
        packages:
          - qemu-guest-agent
          - curl
          - open-iscsi
          - nfs-common
        write_files:
          - path: /etc/modules-load.d/k8s.conf
            content: |
              br_netfilter
              overlay
          - path: /etc/sysctl.d/99-k8s.conf
            content: |
              net.ipv4.ip_forward=1
              net.bridge.bridge-nf-call-iptables=1
              net.bridge.bridge-nf-call-ip6tables=1
        runcmd:
          - systemctl enable --now qemu-guest-agent
          - systemctl enable --now iscsid || true
          - swapoff -a
          - sed -i '/\sswap\s/ s/^/#/' /etc/fstab

