apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: microos3-rootdisk
  namespace: default
spec:
  source:
    pvc:
      namespace: default
      name: opensuse-microos.x86_64-containerhost-kvm-and-xen.qcow2
  pvc:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 64Gi