apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: microos3-kvm-rootdisk
  namespace: default
spec:
  source:
    http:
      url: https://download.opensuse.org/tumbleweed/appliances/openSUSE-MicroOS.x86_64-ContainerHost-kvm-and-xen.qcow2
  pvc:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 64Gi