apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: microos3-rootdisk
  namespace: default
spec:
  source:
    pvc:
      namespace: default
      name: image-nvwpj
  pvc:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 64Gi