apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microos-openstack-golden
  namespace: kng-cluster
  annotations:
    harvesterhci.io/imageId: "default/microos-openstack"
  storageClassName: longhorn
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi