apiVersion: v1
kind: Secret
metadata:
  name: microos1-userdata
  namespace: default
type: Opaque
stringData:
  userdata: |
      #cloud-config
      disable_root: false
      ssh_pwauth: true
      users:
        - name: root
          lock_passwd: false
          passwd: "$y$j9T$MjaNW3whk1b0snP5VFaaz1$VAVFdHX0SDje4xgVSk.7k.3VOhC0uUSPE2hEc42aIS9"
          ssh_authorized_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE4SrYkfM8Xu/9cFpqIOb8Y4OJ3WyPYJRB1zMOoTPJQN george@Georgioss-MacBook-Pro.local
