apiVersion: v1
kind: Secret
metadata:
  name: microos1-userdata
  namespace: default
type: Opaque
stringData:
  userdata: |
      #cloud-config
      password: root123
      disable_root: false
      ssh_pwauth: true
      packages:
        - qemu-guest-agent