apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kng-01-disk
  namespace: default
  annotations:
    harvesterhci.io/imageId: default/ubuntu-2403
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: harvester-longhorn
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: kng-01
  namespace: default
  annotations:
    harvesterhci.io/vmRunStrategy: RerunOnFailure
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '["default/george"]'
      creationTimestamp: null
      labels:
        harvesterhci.io/vmName: kng-01
    spec:
      hostname: kng-01
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        resources:
          requests:
            memory: 4Gi
        devices:
          disks:
            - name: root
              bootOrder: 1
              disk:
                bus: virtio
            - disk:
                bus: virtio
              name: cloudinitdisk
      volumes:
        - name: root
          persistentVolumeClaim:
            claimName: kng-01-disk
        - cloudInitNoCloud: