apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: kng-01
  namespace: kng-cluster
  annotations:
    harvesterhci.io/vmRunStrategy: RerunOnFailure
    harvesterhci.io/os: linux
    harvesterhci.io/maintain-mode-strategy: ShutdownAndRestartAfterEnable
spec:
  runStrategy: RerunOnFailure
  dataVolumeTemplates:
    - metadata:
        name: kng-01-disk
      spec:
        storage:
          storageClassName: longhorn-microos-openstack
          resources:
            requests:
              storage: 64Gi
        source:
          pvc:
            name: microos-openstack-golden
            namespace: kng-cluster
  template:
    metadata:
      labels:
        harvesterhci.io/vmName: kng-01
      annotations:
        harvesterhci.io/sshNames: '["default/george"]'
    spec:
      hostname: kng-01
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        memory:
          guest: 16Gi
        resources:
          requests:
            cpu: "2"
            memory: 16Gi
        devices:
          disks:
            - name: disk-0
              bootOrder: 1
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              bridge: {}
              model: virtio
      networks:
        - name: default
          multus:
            networkName: kng-cluster/k8s-network 
      terminationGracePeriodSeconds: 120
      evictionStrategy: LiveMigrate
      volumes:
        - name: disk-0
          dataVolume:
            name: kng-01-disk
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkDataSecretRef:
              name: cloudinit-common
            secretRef:
              name: cloudinit-common