apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: microos3
  namespace: default
  annotations:
    harvesterhci.io/sshNames: default/george
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: microos3
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: nic0
              model: virtio
              bridge: {}
      networks:
        - name: nic0
          multus:
            networkName: default/k8s-network
      volumes:
        - name: rootdisk
          dataVolume:
            name: microos3-rootdisk
        - name: cloudinit
          cloudInitConfigDrive:
              userData: |
                #cloud-config
                ssh_pwauth: true
                hostname: k8s-01
                users:
                - name: root
                  lock_passwd: false
                  passwd: $6$MA6v7JyQGJABpN4F$eNXET.twXmaFBetvuqbxR5Vd7TjZkKrbE33keFr.XygHjyq220/cUyvIVFWp9hUhG66oh4lFum9V1jdQt4A/6.
                  ssh_authorized_keys:
                    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE4SrYkfM8Xu/9cFpqIOb8Y4OJ3WyPYJRB1zMOoTPJQN george@Georgioss-MacBook-Pro.local
                chpasswd:
                  expire: false
                  list: |
                    root:$6$MA6v7JyQGJABpN4F$eNXET.twXmaFBetvuqbxR5Vd7TjZkKrbE33keFr.XygHjyq220/cUyvIVFWp9hUhG66oh4lFum9V1jdQt4A/6.
                runcmd:
                  - [ /usr/sbin/transactional-update, "-n", "run", "sh", "-c", "zypper -n in qemu-guest-agent && systemctl enable qemu-guest-agent.service" ]
                  - [ /usr/sbin/transactional-update, -n, run, bash, -lc, "cat >/etc/NetworkManager/system-connections/primary.nmconnection <<'EOF'\n[connection]\nid=primary\ntype=ethernet\ninterface-name=enp1s0\nautoconnect=true\n\n[ipv4]\naddress1=10.0.2.150/24,10.0.2.1\ndns=1.1.1.1;8.8.8.8\nmethod=manual\n\n[ipv6]\nmethod=ignore\nEOF\nchmod 600 /etc/NetworkManager/system-connections/primary.nmconnection" ]
                  - [ /usr/sbin/transactional-update, "-n", "run", "sh", "-c", "nmcli con up primary" ]

                power_state:
                  mode: reboot
                  message: "Reboot to activate QGA snapshot"
                  timeout: 30
                  condition: true