apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: microos2
  namespace: default
  annotations:
    harvesterhci.io/sshNames: default/george
    harvesterhci.io/cloudInitUserData: microos1-userdata
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          dataVolume:
            name: microos2-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataSecretRef:
              name: microos-userdata