apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: microos2
  namespace: default
  annotations:
    harvesterhci.io/sshNames: default/george
    harvesterhci.io/cloudInitUserData: microos1-userdata
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
      volumes:
        - name: rootdisk
          dataVolume:
            name: microos2-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
              - name: root
                lock_passwd: false
                passwd: "$y$j9T$PPGS2ZmcEwK9Rva6ijffv.$FfSLRBTa9rctOyzshG6s77Gasi8pXaiInQ635D9TJZ5"
                ssh_authorized_keys:
                  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE4SrYkfM8Xu/9cFpqIOb8Y4OJ3WyPYJRB1zMOoTPJQN george@Georgioss-MacBook-Pro.local"
            networkData: |
              version: 2
              ethernets:
                ens18:
                  dhcp4: false
                  dhcp6: true
                  addresses: [ "10.0.2.50/24" ]
                  gateway4: 10.0.2.1
                  nameservers:
                    addresses: [10.0.1.1]