cloudConfigPath: /etc/kubernetes/cloud-config
kube-vip:
  enabled: false
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"