cloudConfigPath: /etc/kubernetes/cloud-config
kube-vip:
  enabled: false
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
    operator: Exists
  image:
    repository: rancher/mirrored-kube-vip-kube-vip-iptables
    tag: v0.8.7
  env:
    vip_interface: "enp1s0"
    vip_arp: "true"
    lb_enable: "false"
    lb_port: "6443"
    vip_cidr: "32"
    cp_enable: "false"
    svc_enable: "false"
    vip_leaderelection: "false"
    enable_service_security: "false"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
