resources:
  - ../control-planes
patches:
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: base-vm
    patch: |-
      - op: replace
        path: /metadata/name
        value: kng-01
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: kng-01
    path: patch.yaml