namespace: kng-cluster
resources:
  - cloudinit-secret.yaml
  - ../base

patches:
  - target:
      group: kubevirt.io
      version: v1
      kind: VirtualMachine
      name: base-vm
    patch: |-
      - op: replace
        path: /metadata/name
        value: kng-01
      - op: replace
        path: /spec/template/spec/hostname
        value: kng-01
      - op: replace
        path: /spec/template/spec/domain/cpu/cores
        value: 2
      - op: replace
        path: /spec/template/spec/domain/memory/guest
        value: 16Gi
      - op: replace
        path: /spec/dataVolumeTemplates/0/metadata/name
        value: kng-01-disk
      - op: replace
        path: /spec/template/spec/volumes/0/dataVolume/name
        value: kng-01-disk
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud/secretRef/name
        value: kng01-cloudinit-secret
      - op: replace
        path: /spec/template/spec/volumes/1/cloudInitNoCloud/networkDataSecretRef/name
        value: kng01-cloudinit-secret