apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: kng-01
  annotations:
    harvesterhci.io/volumeClaimTemplates: |
      [
        {
          "metadata": {
            "name": "kng-01",
            "annotations": {
              "harvesterhci.io/imageId": "default/microos-openstack"
            }
          },
          "spec": {
            "accessModes": [
              "ReadWriteMany"
            ],
            "resources": {
              "requests": {
                "storage": "64Gi"
              }
            },
            "volumeMode": "Block",
            "storageClassName": "longhorn-microos-openstack"
          }
        }
      ]
spec:
  template:
    spec:
      hostname: kng-01
      volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: kng-01
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: cloudinit-secret
      domain:
        devices:
          interfaces:
            - name: default
              macAddress: 02:00:00:00:10:01
              bridge: {}
              model: virtio